spring.datasource.url=jdbc:postgresql://dpg-d8nrl7po3t8c73d497cg-a.singapore-postgres.render.com/nagarsetu_arie
spring.datasource.username=jatin_garg
spring.datasource.password=uOHuPyKpNjUeNHH1EaECOcXMgZKrabJh


# Redis Cloud Connection Settings
#spring.data.redis.host=https://humorous-polliwog-127220.upstash.io
#spring.data.redis.port=6379
#spring.data.redis.password=gQAAAAAAAfD0AAIgcDJhY2UyYTU2OWM2OTk0YjZkYTI2ZmYyNzE4MDZkZjI3MQ
# ===============================
# UPSTASH REDIS CONFIGURATION
# ===============================
spring.data.redis.url=rediss://default:gQAAAAAAAfD0AAIgcDJhY2UyYTU2OWM2OTk0YjZkYTI2ZmYyNzE4MDZkZjI3MQ@humorous-polliwog-127220.upstash.io:6379
spring.data.redis.ssl.enabled=true