spring.datasource.url=jdbc:postgresql://dpg-d6vbmgvafjfc73culd3g-a.singapore-postgres.render.com/nagarsetu
spring.datasource.username=mcddelhi
spring.datasource.password=eRTFj51dRtgt4DCnSutkvC51KNea5Gp2